# Generated by Django 4.1.7 on 2023-04-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontact',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='usercontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
