# Generated by Django 4.1.7 on 2023-04-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contactdetails_id_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer_image',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='review_img'),
        ),
    ]
