# Generated by Django 4.1.7 on 2023-04-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_review_reviewer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(max_length=250)),
                ('instagram', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_image',
            field=models.ImageField(blank=True, default='review_img/avatar.svg', null=True, upload_to='review_img'),
        ),
    ]
