# Generated by Django 4.1.7 on 2023-06-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_projects_project_image2_alter_projects_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Software Development', 'Software Development'), ('Mobile App Development', 'Mobile App Development'), ('E-commerce Solutions', 'E-commerce Solutions'), ('Graphic Design', 'Graphic Design'), ('Digital Marketing', 'Digital Marketing')], max_length=150),
        ),
    ]
