# Generated by Django 4.1.7 on 2023-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_projects_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
